apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: lucj/voting:vote
        name: vote
        ports:
        - containerPort: 80
          name: vote
        resources:
          limits:
            cpu: 80m
            memory: 256Mi
          requests:
            cpu: 80m
            memory: 256Mi
