apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: lucj/voting:worker
        name: worker
        resources:
          limits:
            cpu: 80m
            memory: 128Mi
          requests:
            cpu: 80m
            memory: 128Mi
